### ISSUE TITLE
Manuals/Instructions for Sample Sketches

### ISSUE THREAD

**Issue by simonjhutchinson** [logickworkshop/du-ino#11]
Hi! Not really an "issue", but it would be great to have some documentation about using example sketches. 

I've figured out the quantizer and ADSR, but I'm a little stumped by the stochastic sequencer--not sure how to add more than one row to the sequence, and not sure that my clock is properly driving it. Some very quick instructions might be most appreciated!

Thanks!

**Comment by ezod** [comment]
I've been wanting to do this for a long time and never really settled on a format for it. I took a stab at a web-based format today in 2dcc5a8982d225e9a22d11c1520e7b35c90fd283. I'm not really a HTML/CSS person so this surely needs aesthetic work, but it's a start.

**Comment by simonjhutchinson** [comment]
Wow! This looks great!

What I had a lot of trouble with at first was the interface and interactions of each patch (what does a click do? what does a double-click do? What are the different display parts showing, if applicable?). I think it might be a good idea to include these for each of the examples. The ADSR is actually the most straightforward in some ways!

The visuals here are right on, though. Nice work.

**Comment by ezod** [comment]
The next step is documenting the interface. For the callouts, I need to come up with something a little more elaborate than with the jacks, since the UI elements can have arbitrary positions and sizes, but I think it's doable without too much fuss. In addition to those, I'll add a section below describing general UI navigation (i.e. what the 3 encoder actions do).
